CREATE TABLE M31.SPRING_TIMELOG_THING
(
  id NUMBER NOT NULL,
  thing VARCHAR2(80),
  view_order NUMBER DEFAULT 0,
  member_id NUMBER,
  CONSTRAINT PK_SPRING_TIMELOG_THING PRIMARY KEY(id),
  CONSTRAINT FK_SPRING_TIMELOG_THING FOREIGN KEY(member_id) REFERENCES M31.MEMBER(ID)
);

CREATE TABLE M31.SPRING_TIMELOG_MEMBER_THING
(
  thing_id NUMBER,
  member_id NUMBER,
  reg_date DATE DEFAULT sysdate,
  CONSTRAINT PK_SPRING_TIMELOG_MEMBER_THING PRIMARY KEY(thing_id,member_id),
  CONSTRAINT FK_SP_TIMELOG_MEMBER_THING FOREIGN KEY(member_id) REFERENCES M31.MEMBER(ID),
  CONSTRAINT FK_SP_TIMELOG_MEMBER_THING2 FOREIGN KEY(thing_id) REFERENCES M31.SPRING_TIMELOG_THING(ID)
);

/*Thin 기본값*/
INSERT into SPRING_TIMELOG_THING values(TIMELOG_THING_SEQ.NEXTVAL, '흡연', 0, 21);
INSERT into SPRING_TIMELOG_THING values(TIMELOG_THING_SEQ.NEXTVAL, '화장실', 0, 21);
INSERT into SPRING_TIMELOG_THING values(TIMELOG_THING_SEQ.NEXTVAL, '일', 0, 21);
INSERT into SPRING_TIMELOG_THING values(TIMELOG_THING_SEQ.NEXTVAL, '밥', 0, 21);